### ISSUE TITLE
TODO - Meeting 2023-08-03

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#63]
# Channel
- [ ] Kick Issue
> As owner, you kick a user.
> But the kicked user does not get the feedback and his channel window where he was kicked.

- #26
> As  a user,  go to the channel and checks for a friend in the searchbar
> friends appears twice

- #58 
- #15 
> As Amina user, create a friend private room with a friend Alicia.
> Recreate a room with a friend Alicia is possible.

- #60 
> As user, if i chat with a friend => in the header of the window chat, it's my avatar and my name that appears

#65
- [ ] Not found friend to create private channel

#66
- [ ] Error FireFox Socket issue in inspector
> Error Firefox in inspector when the user goes to channel component

# Global
- [x] #62 
> When the user quit the application without using Logout and Login again
> Error in inspcetor about ChannelSlice
> Solution: Clear the store REDUX ?

- [ ] Check auth user to access all routes

- [ ] CSS made by Alicia ?
> Stay on this CSS
